const GameActionTypes = {
    NEW_GAME: 'NEW_GAME',
    UPDATE_GAME: 'UPDATE_GAME',
    UPDATE_CELL: 'UPDATE_CELL',
    SOLVE_GAME: 'SOLVE_GAME',
    VALIDATE_GAME: 'VALIDATE_GAME',
    RESET_GAME: 'RESET_GAME',
    CHANGE_DIFFICULTY: 'CHANGE_DIFFICULTY',
    SELECT_NUMBER: 'SELECT_NUMBER',
    SELECT_CELL: 'SELECT_CELL',
    TOGGLE_PENCIL: 'TOGGLE_PENCIL',
    UPDATE_PENCIL_ARRAYS: 'UPDATE_PENCIL_ARRAYS',
    HINT_REQUEST: 'HINT_REQUEST',
    INCREASE_TIMER: 'INCREASE_TIMER',
    ADD_SCORE: 'ADD_SCORE',
    RESET_SCORES: 'RESET_SCORES',
    CHECK_SOLUTION: 'CHECK_SOLUTION',
}

export default GameActionTypes;